# Generated by Django 2.0.5 on 2018-06-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('partia', models.CharField(max_length=20)),
                ('zdjecie', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba_gl', models.IntegerField()),
                ('id_Kandynaci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Kandydat')),
            ],
        ),
        migrations.CreateModel(
            name='osoba_gl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pesel', models.CharField(max_length=10)),
                ('haslo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wybory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('data_pocz', models.DateTimeField(max_length=20)),
                ('ilosc', models.IntegerField()),
                ('wybor', models.CharField(choices=[('t', 'tak'), ('n', 'nie')], max_length=2)),
                ('data_koncowa', models.DateTimeField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lista_k',
            name='id_wybory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Wybory'),
        ),
        migrations.AddField(
            model_name='lista',
            name='id_osoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.osoba_gl'),
        ),
        migrations.AddField(
            model_name='lista',
            name='id_wybory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Wybory'),
        ),
        migrations.AddField(
            model_name='kandydat',
            name='id_wybory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Wybory'),
        ),
    ]
