# Generated by Django 2.0.5 on 2018-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180605_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='zdjecie',
            field=models.ImageField(upload_to='img'),
        ),
    ]
