# Generated by Django 2.0.5 on 2018-06-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180607_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='zdjecie',
            field=models.ImageField(upload_to='C:/Users/2esie/Desktop/Wybory/mainapp/static/img'),
        ),
    ]
