# Generated by Django 2.0.5 on 2018-06-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180607_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='zdjecie',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
